apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-staging
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: gcr.io/YOUR_PROJECT_ID/hello-world:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "staging"
